"""initial

Revision ID: 04b137d1f753
Revises:
Create Date: 2023-10-21 23:24:18.706492

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04b137d1f753"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column("id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("owner_id", sa.BIGINT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="tntb",
    )
    op.create_table(
        "streamers",
        sa.Column("id", sa.String(), autoincrement=False, nullable=False),
        sa.Column("subscription_id", sa.String(), nullable=False),
        sa.Column("last_message", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="tntb",
    )
    op.create_table(
        "subscriptions",
        sa.Column("chat_id", sa.BIGINT(), nullable=False),
        sa.Column("streamer_id", sa.String(), nullable=False),
        sa.Column("message_template", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("chat_id", "streamer_id"),
        schema="tntb",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subscriptions", schema="tntb")
    op.drop_table("streamers", schema="tntb")
    op.drop_table("chats", schema="tntb")
    # ### end Alembic commands ###
