"""sub picture id

Revision ID: 8cf6e663ddad
Revises: 72a15f0135d1
Create Date: 2024-10-31 01:05:03.048918

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8cf6e663ddad"
down_revision: Union[str, None] = "72a15f0135d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriptions",
        sa.Column("picture_id", sa.String(), nullable=True),
        schema="tntb",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "picture_id", schema="tntb")
    # ### end Alembic commands ###
