"""picture mode

Revision ID: 8774b1211750
Revises: 06988deef2e4
Create Date: 2024-10-19 13:18:34.175894

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8774b1211750"
down_revision: Union[str, None] = "06988deef2e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    op.add_column(
        "subscriptions",
        sa.Column("picture_mode", sa.String(), nullable=True),
        schema="tntb",
    )
    conn.execute(
        sa.text("UPDATE tntb.subscriptions SET picture_mode='Stream start screen';")
    )
    op.alter_column(
        "subscriptions",
        "picture_mode",
        existing_type=sa.String(),
        nullable=False,
        schema="tntb",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "picture_mode", schema="tntb")
    # ### end Alembic commands ###
