"""users

Revision ID: 72a15f0135d1
Revises: 8774b1211750
Create Date: 2024-10-26 22:19:26.150655

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72a15f0135d1"
down_revision: Union[str, None] = "8774b1211750"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("limit", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="tntb",
    )
    conn = op.get_bind()
    conn.execute(
        sa.text("INSERT INTO tntb.users (id) SELECT DISTINCT user_id FROM tntb.chats;")
    )
    conn.execute(sa.text("UPDATE tntb.users SET name = id;"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users", schema="tntb")
    # ### end Alembic commands ###
