"""streamer name

Revision ID: a1292ee22287
Revises: 04b137d1f753
Create Date: 2024-10-10 01:15:33.709606

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1292ee22287"
down_revision: Union[str, None] = "04b137d1f753"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "streamers",
        sa.Column("name", sa.String(), nullable=True),
        schema="tntb",
    )
    conn = op.get_bind()
    conn.execute(sa.text("UPDATE tntb.streamers SET name='-';"))
    op.alter_column(
        "streamers",
        "name",
        existing_type=sa.String(),
        nullable=False,
        schema="tntb",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("streamers", "name", schema="tntb")
    # ### end Alembic commands ###
