"""picture_mode

Revision ID: bedecf3f1670
Revises: 04b137d1f753
Create Date: 2024-02-09 22:29:02.381306

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bedecf3f1670"
down_revision: Union[str, None] = "04b137d1f753"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriptions",
        sa.Column("picture_mode", sa.String(), nullable=True),
        schema="tntb",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "picture_mode", schema="tntb")
    # ### end Alembic commands ###
