"""restreams_links

Revision ID: 977e6d7e9bc7
Revises: 8cf6e663ddad
Create Date: 2025-03-04 00:15:28.567640

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "977e6d7e9bc7"
down_revision: Union[str, None] = "8cf6e663ddad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriptions",
        sa.Column("restreams_links", sa.JSON(), nullable=True),
        schema="tntb",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "restreams_links", schema="tntb")
    # ### end Alembic commands ###
