"""streamers last message timestamp

Revision ID: ae892176eeee
Revises: 977e6d7e9bc7
Create Date: 2025-03-26 00:03:02.151614

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae892176eeee"
down_revision: Union[str, None] = "977e6d7e9bc7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    op.add_column(
        "streamers",
        sa.Column(
            "last_message_timestamp",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
        ),
        schema="tntb",
    )
    conn.execute(
        sa.text(
            "UPDATE tntb.streamers SET last_message_timestamp='1970-01-01 00:00+00:00';"
        )
    )
    op.alter_column(
        "streamers",
        "last_message_timestamp",
        existing_type=sa.TIMESTAMP(timezone=True),
        nullable=False,
        schema="tntb",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("streamers", "last_message_timestamp", schema="tntb")
    # ### end Alembic commands ###
