name: Deploy app
run-name: Deploy app from branch ${{ github.ref_name }} to PROD with ${{ inputs.docker_port }} port

on:
  workflow_dispatch:
    inputs:
      docker_port:
        description: "Port for running docker"
        default: '8802'

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push docker
    permissions:
      contents: read
      packages: write
    outputs:
      full_image_name: ${{ steps.define_image_names.outputs.FULL_IMAGE_NAME }}
      image_name: ${{ steps.define_image_names.outputs.IMAGE_NAME }}
    steps:
      - name: Lower case image name
        id: define_image_names
        env:
          FULL_REPO: ${{ github.repository }}
          REPO: ${{ github.event.repository.name }}
        run: |
          echo "FULL_IMAGE_NAME=${FULL_REPO,,}/prod" >>${GITHUB_OUTPUT}
          echo "IMAGE_NAME=${REPO,,}/prod" >>${GITHUB_OUTPUT}
      - name: Check out branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_GH }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ steps.define_image_names.outputs.FULL_IMAGE_NAME }}:latest

  alembic:
    runs-on: ubuntu-latest
    name: Alembic
    steps:
      - name: Check out branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - name: TAR code
        run: tar -cvf tntb-prod.tar .
      - name: Copy code to host
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          source: "tntb-prod.tar"
          target: "~/builds"
      - name: Apply alembic
        uses: appleboy/ssh-action@v1.0.0
        env:
          TNTB__DB_DSN: ${{ secrets.DB_DSN_TNTB_PROD }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            mkdir ~/builds/tntb-prod
            tar -xf ~/builds/tntb-prod.tar -C ~/builds/tntb-prod/
            cd ~/builds/tntb-prod/
            export TNTB_DB_DSN=${{ env.TNTB__DB_DSN }}
            python3 -m alembic upgrade head
            cd ~
            rm ~/builds/tntb-prod.tar
            sudo rm -rf ~/builds/tntb-prod

  deploy:
    runs-on: ubuntu-latest
    name: Deploy docker
    needs: [build, alembic]
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        env:
          TNTB_DEPLOY_FULL_IMAGE_NAME: ${{ needs.build.outputs.full_image_name }}
          TNTB_DEPLOY_PAT_GH: ${{ secrets.PAT_GH }}
          TNTB_DEPLOY_GH_LOGIN: ${{ github.actor }}
          TNTB_DEPLOY_DOCKER_PORT: ${{ inputs.docker_port }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            docker login ${{ env.DOCKER_REGISTRY }} -u ${{ env.TNTB_DEPLOY_GH_LOGIN }} -p ${{ env.TNTB_DEPLOY_PAT_GH }}
            echo "-------- Try to stop tntb-prod container"
            docker stop tntb-prod || true
            echo "-------- Try to delete tntb-prod container"
            docker container rm tntb-prod || true
            echo "-------- Try to delete ${{ env.TNTB_DEPLOY_FULL_IMAGE_NAME }} image"
            docker rmi ${{ env.DOCKER_REGISTRY }}/${{ env.TNTB_DEPLOY_FULL_IMAGE_NAME }} || true
            echo "-------- Try to pull and run ${{ env.TNTB_DEPLOY_FULL_IMAGE_NAME }} image"
            docker run -d \
              -it \
              --name tntb-prod \
              --restart always \
              --network=host \
              -e APP_HOST=127.0.0.1 \
              -e APP_PORT=${{ env.TNTB_DEPLOY_DOCKER_PORT }} \
              -e APP_ENV=prod \
              --mount type=bind,source=/home/${{ env.TNTB_DEPLOY_GH_LOGIN }}/deploy_configs/tntb-prod/config.yaml,target=/application/config/config.yaml \
              ${{ env.DOCKER_REGISTRY }}/${{ env.TNTB_DEPLOY_FULL_IMAGE_NAME }}:latest
            docker logout "${{ env.DOCKER_REGISTRY }}"

      - name: Delete old images
        uses: actions/delete-package-versions@v4
        if: ${{ always() }}
        with:
          package-name: ${{ needs.build.outputs.image_name }}
          package-type: 'container'
          min-versions-to-keep: 1
          token: ${{ secrets.PAT_GH }}
